source 'https://cdn.cocoapods.org'
source 'https://github.com/WZLYiOS/WZPodSpecs.git'

platform :ios, '9.0'
use_frameworks!

target 'WZTabbarController_Example' do
  pod 'WZTabbarController', :path => '../'
  pod 'lottie-ios', '~> 3.1.2'
  pod 'EasyRefresher', '~> 1.2.1'
  pod 'RPCircularProgress', '~> 0.5.0'
end
