source 'https://cdn.cocoapods.org'
#source 'https://github.com/WZLYiOS/WZPodSpecs.git'

platform :ios, '12.0'
use_frameworks!

target 'WZTabbarController_Example' do
  pod 'WZTabbarController', :path => '../'
  pod 'lottie-ios', '~> 3.1.2'
  pod 'EasyRefresher', '~> 1.2.1'
  pod 'RPCircularProgress', '~> 0.5.0'
  pod 'WZTransition'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 12.0
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
  end
end
